# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1edbe10dc9851a8e59aa2a6756c9c9a4fd79e1df7e035f38fc256852fb0f046a4f87641a6f2ffe800d1f4b6091e4fd526e7a11e9deef3bbe71812e370f2dacf

test:
  secret_key_base: 3b7bd065b1b75ddee55b301e685b377d4b0ffb6802f80e2d9e229e5577f20575723102df99b89fbd752efd20ba7cb3bd9f35a3cf55b51959fbe8f4915ad3a1a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
